[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --chip esp32s3 --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["alloc", "core"]

[env]
ESP_LOG = "INFO"
