[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --chip esp32c6 --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["alloc", "core"]

[env]
ESP_LOG = "INFO"
