//! Linear (interrupt-per-transfer) refresh state machine.
//!
//! One DMA transfer per BCM segment group; the ISR rebuilds the descriptor
//! chain and restarts the transfer at every completion. Buffer swaps apply a
//! pointer delta to the cached segments at a frame boundary.
//!
//! This module is compiled only when the `circular-dma` feature is **not**
//! enabled. Its circular counterpart lives in [`super::circular`].

use core::sync::atomic::AtomicBool;
use core::sync::atomic::Ordering;

use esp_hal::Blocking;
use esp_hal::handler;
#[cfg(feature = "iram")]
use esp_hal::ram;

use super::SWAP_DONE;
use super::Shared;
use super::signal_swap_done;
use crate::Hub75Error;
use crate::bcm::cache_ptr;
use crate::bcm::linear::LinearBcmBuf;
use crate::bcm::segments_from_fb_into;
use crate::framebuffer::FrameBuffer;
#[cfg(hub75_use_lcd_cam)]
use crate::framebuffer::WordSize;

// ---------------------------------------------------------------------------
// Platform-specific type aliases
// ---------------------------------------------------------------------------

#[cfg(hub75_use_i2s_parallel)]
pub(crate) type TxDriver = esp_hal::i2s::parallel::I2sParallel<'static, Blocking>;

#[cfg(hub75_use_i2s_parallel)]
pub(crate) type TxTransfer =
    esp_hal::i2s::parallel::I2sParallelTransfer<'static, LinearBcmBuf, Blocking>;

#[cfg(hub75_use_parl_io)]
pub(crate) type TxDriver = esp_hal::parl_io::ParlIoTx<'static, Blocking>;

#[cfg(hub75_use_parl_io)]
pub(crate) type TxTransfer = esp_hal::parl_io::ParlIoTxTransfer<'static, LinearBcmBuf, Blocking>;

#[cfg(hub75_use_lcd_cam)]
pub(crate) type TxDriver = esp_hal::lcd_cam::lcd::i8080::I8080<'static, Blocking>;

#[cfg(hub75_use_lcd_cam)]
pub(crate) type TxTransfer =
    esp_hal::lcd_cam::lcd::i8080::I8080Transfer<'static, LinearBcmBuf, Blocking>;

// ---------------------------------------------------------------------------
// ISR shared state
// ---------------------------------------------------------------------------

pub(crate) enum TransferPhase {
    Idle(TxDriver, LinearBcmBuf),
    InFlight(TxTransfer),
    Error(Hub75Error, TxDriver, LinearBcmBuf),
    Transitioning,
}

/// Linear-mode ISR state. Mirror of [`super::circular::State`]: both carry
/// `current_fb_ptr` + `pending_delta` for the pointer-delta swap protocol;
/// the fields above those two are mode-specific.
pub(crate) struct State {
    pub(crate) transfer: TransferPhase,
    #[cfg(hub75_use_lcd_cam)]
    pub(crate) word_size: crate::framebuffer::WordSize,

    pub(crate) current_fb_ptr: *const (),
    /// Byte offset from the current to the pending framebuffer, set by
    /// `swap()`. The ISR applies this delta to every cached segment
    /// pointer at the frame boundary, then clears it to `None`. The new
    /// framebuffer pointer is derived from this delta, so no separate
    /// `pending_fb_ptr` field is needed (mirroring `circular::State`).
    pub(crate) pending_delta: Option<isize>,
}

// SAFETY (`Send`): required so the `Mutex<RefCell<Option<_>>>` statics below
// are `Sync`. All access to the inner value is serialised by the embassy
// mutex (which disables interrupts and CAS-spins on an owner word on
// multi-core chips). The raw pointer `current_fb_ptr` is only dereferenced
// inside lock closures, so it is never accessed concurrently from multiple
// cores.
unsafe impl Send for State {}

type SharedState = Shared<Option<State>>;

static STATE: SharedState = Shared::new(None);

/// DMA error flag, set by the ISR when a transfer fails. Cleared by
/// `start_internal` when refresh is (re)started. Consumers treat it as an
/// alternate completion condition for a pending swap.
pub(crate) static HAS_ERROR: AtomicBool = AtomicBool::new(false);

// ---------------------------------------------------------------------------
// Platform-specific transfer helpers
// ---------------------------------------------------------------------------

#[cfg(hub75_use_i2s_parallel)]
#[cfg_attr(feature = "iram", ram)]
fn start_transfer(
    tx: TxDriver,
    buf: LinearBcmBuf,
) -> Result<TxTransfer, (Hub75Error, TxDriver, LinearBcmBuf)> {
    tx.send(buf)
        .map_err(|(err, tx, buf)| (Hub75Error::Dma(err), tx, buf))
}

#[cfg(hub75_use_i2s_parallel)]
#[cfg_attr(feature = "iram", ram)]
fn finish_transfer(xfer: TxTransfer) -> (Result<(), Hub75Error>, TxDriver, LinearBcmBuf) {
    let (tx, buf) = xfer.wait();
    (Ok(()), tx, buf)
}

/// On ESP32-C5, the GDMA EOF signal is generated by the DMA channel rather
/// than the `PARL_IO` byte counter, so the transfer-length field is unused.
#[cfg(all(hub75_use_parl_io, esp32c5))]
pub(crate) const PARL_IO_DUMMY_TRANSFER_LEN: usize = 0;

#[cfg(hub75_use_parl_io)]
#[cfg_attr(feature = "iram", ram)]
fn start_transfer(
    tx: TxDriver,
    buf: LinearBcmBuf,
) -> Result<TxTransfer, (Hub75Error, TxDriver, LinearBcmBuf)> {
    #[cfg(esp32c5)]
    let transfer_len = PARL_IO_DUMMY_TRANSFER_LEN;
    #[cfg(not(esp32c5))]
    let transfer_len = buf.current_transfer_len();

    tx.write(transfer_len, buf)
        .map_err(|(err, tx, buf)| (Hub75Error::ParlIo(err), tx, buf))
}

#[cfg(hub75_use_parl_io)]
#[cfg_attr(feature = "iram", ram)]
fn finish_transfer(xfer: TxTransfer) -> (Result<(), Hub75Error>, TxDriver, LinearBcmBuf) {
    let (result, tx, buf) = xfer.wait();
    (result.map_err(Hub75Error::Dma), tx, buf)
}

#[cfg(hub75_use_lcd_cam)]
#[cfg_attr(feature = "iram", ram)]
fn start_transfer(
    tx: TxDriver,
    buf: LinearBcmBuf,
    word_size: WordSize,
) -> Result<TxTransfer, (Hub75Error, TxDriver, LinearBcmBuf)> {
    use esp_hal::lcd_cam::lcd::i8080::Command;

    let result = match word_size {
        WordSize::Eight => tx.send(Command::<u8>::None, 0, buf),
        WordSize::Sixteen => tx.send(Command::<u16>::None, 0, buf),
    };
    result.map_err(|(err, tx, buf)| (Hub75Error::Dma(err), tx, buf))
}

// ---------------------------------------------------------------------------
// Interrupt handler
// ---------------------------------------------------------------------------

#[handler]
#[cfg_attr(feature = "iram", ram)]
pub(crate) fn isr() {
    STATE.with(|state| {
        let Some(state) = state.as_mut() else { return };

        let xfer = match core::mem::replace(&mut state.transfer, TransferPhase::Transitioning) {
            TransferPhase::InFlight(xfer) => xfer,
            other => {
                state.transfer = other;
                return;
            }
        };

        // .wait() returns instantly — the interrupt already fired.
        let (result, tx, mut buf) = finish_transfer(xfer);

        if let Err(err) = result {
            state.transfer = TransferPhase::Error(err, tx, buf);
            HAS_ERROR.store(true, Ordering::Release);
            signal_swap_done();
            return;
        }

        let frame_boundary = buf.advance();

        if frame_boundary && let Some(delta) = state.pending_delta.take() {
            state.current_fb_ptr = state.current_fb_ptr.wrapping_byte_offset(delta);
            buf.apply_delta(delta);
            signal_swap_done();
        }

        #[cfg(hub75_use_lcd_cam)]
        let xfer_result = start_transfer(tx, buf, state.word_size);
        #[cfg(not(hub75_use_lcd_cam))]
        let xfer_result = start_transfer(tx, buf);

        match xfer_result {
            Ok(new_xfer) => {
                state.transfer = TransferPhase::InFlight(new_xfer);
            }
            Err((hub_err, tx, buf)) => {
                state.transfer = TransferPhase::Error(hub_err, tx, buf);
                HAS_ERROR.store(true, Ordering::Release);
                signal_swap_done();
            }
        }
    });
}

// ---------------------------------------------------------------------------
// ISR state initialisation (called by platform constructors)
// ---------------------------------------------------------------------------

#[cfg(not(hub75_use_lcd_cam))]
pub(crate) fn init_state(tx: TxDriver, buf: LinearBcmBuf) {
    STATE.with(|state| {
        *state = Some(State {
            transfer: TransferPhase::Idle(tx, buf),
            current_fb_ptr: core::ptr::null(),
            pending_delta: None,
        });
    });
}

#[cfg(hub75_use_lcd_cam)]
pub(crate) fn init_state(tx: TxDriver, buf: LinearBcmBuf, word_size: WordSize) {
    STATE.with(|state| {
        *state = Some(State {
            transfer: TransferPhase::Idle(tx, buf),
            word_size,
            current_fb_ptr: core::ptr::null(),
            pending_delta: None,
        });
    });
}

// ---------------------------------------------------------------------------
// Start / restart
// ---------------------------------------------------------------------------

pub(crate) fn start_internal(fb: &'static impl FrameBuffer) -> Result<(), Hub75Error> {
    crate::bcm::validate_fb_internal_ram(fb);

    STATE.with(|state| {
        let state = state.as_mut().expect("Hub75 not initialised");

        let (tx, mut buf) =
            match core::mem::replace(&mut state.transfer, TransferPhase::Transitioning) {
                TransferPhase::Idle(tx, buf) | TransferPhase::Error(_, tx, buf) => (tx, buf),
                other => {
                    state.transfer = other;
                    return Err(Hub75Error::AlreadyRunning);
                }
            };

        // Resolve any stale Hub75Swap that was waiting on a previous error
        // state before it was consumed. Without this, a swap left un-waited
        // when restart() is called would spin forever because HAS_ERROR and
        // SWAP_DONE get cleared below, and no new pending_delta exists to
        // drive a fresh completion signal.
        signal_swap_done();

        // Build the cache in-place (restart/re-init path).
        segments_from_fb_into(fb, unsafe { &mut *cache_ptr().cast_mut() });
        buf.reset_with_cache();
        state.current_fb_ptr = core::ptr::from_ref(fb).cast::<()>();
        state.pending_delta = None;

        #[cfg(hub75_use_lcd_cam)]
        let xfer_result = start_transfer(tx, buf, state.word_size);
        #[cfg(not(hub75_use_lcd_cam))]
        let xfer_result = start_transfer(tx, buf);

        match xfer_result {
            Ok(xfer) => {
                state.transfer = TransferPhase::InFlight(xfer);
                HAS_ERROR.store(false, Ordering::Release);
                SWAP_DONE.store(false, Ordering::Release);
                Ok(())
            }
            Err((hub_err, tx, buf)) => {
                state.transfer = TransferPhase::Error(hub_err, tx, buf);
                HAS_ERROR.store(true, Ordering::Release);
                Err(hub_err)
            }
        }
    })
}

#[cfg(hub75_use_lcd_cam)]
#[cfg_attr(feature = "iram", ram)]
fn finish_transfer(xfer: TxTransfer) -> (Result<(), Hub75Error>, TxDriver, LinearBcmBuf) {
    let (result, tx, buf) = xfer.wait();
    (result.map_err(Hub75Error::Dma), tx, buf)
}

// ---------------------------------------------------------------------------
// Hub75::restart (linear only — circular never stops, so has no restart)
// ---------------------------------------------------------------------------

impl<DM: esp_hal::DriverMode, FB: FrameBuffer + 'static> super::Hub75<DM, FB> {
    /// Restart display refresh after an error.
    ///
    /// Callable after [`Hub75::swap`](super::Hub75::swap) returned an error.
    /// Sets up the BCM segment data and kicks off the first DMA transfer with
    /// the same framebuffer type.
    ///
    /// This method is only available when `circular-dma` is **not** enabled.
    /// In circular-DMA mode the DMA engine never stops, so there is no
    /// restart path.
    ///
    /// # Errors
    ///
    /// Returns [`Hub75Error::AlreadyRunning`](crate::Hub75Error::AlreadyRunning)
    /// if called while a transfer is already in flight. Call
    /// [`Hub75Swap::wait`](crate::Hub75Swap::wait) on the outstanding swap
    /// first.
    pub fn restart(&self, fb: &'static FB) -> Result<(), Hub75Error> {
        start_internal(fb)
    }
}

// ---------------------------------------------------------------------------
// Swap
// ---------------------------------------------------------------------------

impl<DM: esp_hal::DriverMode, FB: FrameBuffer + 'static> super::Hub75<DM, FB> {
    /// Initiate a framebuffer swap.
    ///
    /// Registers `new_fb` as the pending buffer. The actual swap occurs at
    /// the next frame boundary (handled by the ISR). Returns a [`Hub75Swap`]
    /// transfer object; call [`.wait_for_done()`](Hub75Swap::wait_for_done)
    /// then [`.wait()`](Hub75Swap::wait), or just `.wait()` directly for
    /// blocking.
    ///
    /// # Errors
    ///
    /// Returns [`Hub75Error::SwapInFlight`] along with ownership of `new_fb`
    /// if a previous [`Hub75Swap`] is still outstanding. Only one swap may be
    /// in-flight at a time; call `.wait()` (or `.wait_for_done().await` then
    /// `.wait()`) on the previous [`Hub75Swap`] before calling `swap()` again.
    ///
    /// # Panics
    ///
    /// Panics if the driver has not been initialised (no `Hub75` instance
    /// was created).
    pub fn swap(
        &self,
        new_fb: &'static mut FB,
    ) -> Result<super::Hub75Swap<FB>, (Hub75Error, &'static mut FB)> {
        // Pre-validate the framebuffer contract so any panic happens outside
        // the critical section (with interrupts enabled).
        let count = new_fb.bcm_segment_count();
        let spg = new_fb.bcm_segments_per_group();
        assert!(
            count <= crate::bcm::MAX_SEGMENTS,
            "bcm_segment_count {count} exceeds MAX_SEGMENTS"
        );
        assert!(
            spg > 0 && count.is_multiple_of(spg),
            "bcm_segment_count {count} not divisible by segments_per_group {spg}"
        );
        let new_fb_ptr = core::ptr::from_mut::<FB>(new_fb);

        let old_fb_ptr = STATE.with(|state| {
            let state = state.as_mut().expect("Hub75 not initialised");
            if state.pending_delta.is_some() {
                return Err(new_fb_ptr as *const ());
            }
            let old = state.current_fb_ptr;
            // Both framebuffers are the same type with identical internal
            // layout; this is the same invariant circular-DMA mode relies
            // on. The delta shifts every cached segment pointer to the new
            // FB.
            let delta = new_fb_ptr as isize - old as isize;
            state.pending_delta = Some(delta);
            SWAP_DONE.store(false, Ordering::Release);
            Ok(old)
        });

        match old_fb_ptr {
            Ok(old) => Ok(super::Hub75Swap {
                old_fb_ptr: old as *mut FB,
                new_fb_ptr,
            }),
            Err(_) => Err((Hub75Error::SwapInFlight, new_fb)),
        }
    }
}

// ---------------------------------------------------------------------------
// Hub75Swap completion (linear)
// ---------------------------------------------------------------------------

impl<FB: FrameBuffer + 'static> super::Hub75Swap<FB> {
    /// Spin-loops until the DMA is guaranteed to no longer be reading from
    /// the old framebuffer, then returns it for reuse.
    ///
    /// In non-circular mode this waits for the next frame boundary. In
    /// circular-DMA mode this waits for one complete frame to be rendered
    /// after the pointer update.
    ///
    /// If [`wait_for_done()`](Self::wait_for_done) was already awaited, this
    /// returns immediately.
    ///
    /// # Errors
    ///
    /// Returns [`Hub75Error::Dma`] if the ISR has recorded a DMA error from
    /// a prior transfer.
    ///
    /// # Panics
    ///
    /// Panics if the driver has not been initialised (no `Hub75` instance
    /// was created).
    pub fn wait(self) -> Result<&'static mut FB, (Hub75Error, &'static mut FB)> {
        loop {
            if HAS_ERROR.load(Ordering::Acquire) {
                return STATE.with(|state| {
                    let state = state.as_mut().unwrap();
                    state.pending_delta = None;
                    let err = match &state.transfer {
                        TransferPhase::Error(err, _, _) => *err,
                        _ => Hub75Error::Dma(esp_hal::dma::DmaError::DescriptorError),
                    };
                    Err((err, unsafe { &mut *self.new_fb_ptr }))
                });
            }
            if SWAP_DONE.load(Ordering::Acquire) {
                break;
            }
            core::hint::spin_loop();
        }
        Ok(unsafe { &mut *self.old_fb_ptr })
    }

    /// Yields to the executor until the swap is complete.
    ///
    /// After this resolves, call [`wait()`](Self::wait) to obtain the old
    /// framebuffer. This mirrors the esp-hal transfer pattern:
    ///
    /// ```rust,ignore
    /// let mut xfer = hub75.swap(fb)?;
    /// xfer.wait_for_done().await;
    /// fb = xfer.wait()?;
    /// ```
    pub async fn wait_for_done(&mut self) {
        core::future::poll_fn(|cx| {
            if SWAP_DONE.load(Ordering::Acquire) || HAS_ERROR.load(Ordering::Acquire) {
                return core::task::Poll::Ready(());
            }
            super::SWAP_WAKER.with(|waker| {
                if SWAP_DONE.load(Ordering::Acquire) || HAS_ERROR.load(Ordering::Acquire) {
                    return core::task::Poll::Ready(());
                }
                *waker = Some(cx.waker().clone());
                core::task::Poll::Pending
            })
        })
        .await;
    }
}
